"""empty message

Revision ID: 20688636cedd
Revises: 598fc9929ba7
Create Date: 2023-11-17 23:08:55.831005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20688636cedd'
down_revision = '598fc9929ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('AdmID', sa.Integer(), nullable=False),
    sa.Column('AdmName', sa.String(length=50), nullable=True),
    sa.Column('Aassword', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('AdmID')
    )
    op.create_table('advertising_id',
    sa.Column('AdvertisingID', sa.Integer(), nullable=False),
    sa.Column('Abstract', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('ReleaseTime', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('Picture', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('AdvertisingID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertising_id')
    op.drop_table('admin')
    # ### end Alembic commands ###
