"""empty message

Revision ID: 3adb000efbc8
Revises: 20688636cedd
Create Date: 2023-11-17 23:16:06.073334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3adb000efbc8'
down_revision = '20688636cedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('广告',
    sa.Column('AdvertisingID', sa.Integer(), nullable=False),
    sa.Column('Abstract', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('ReleaseTime', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('Picture', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('AdvertisingID')
    )
    op.create_table('管理员',
    sa.Column('AdmID', sa.Integer(), nullable=False),
    sa.Column('AdmName', sa.String(length=50), nullable=True),
    sa.Column('Aassword', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('AdmID')
    )
    op.drop_table('admin')
    op.drop_table('登榜')
    op.drop_table('advertising_id')
    op.drop_table('bangdan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bangdan',
    sa.Column('ChartID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ChartType', mysql.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('ChartID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('advertising_id',
    sa.Column('AdvertisingID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Abstract', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('ReleaseTime', mysql.DATETIME(), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('Picture', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('AdvertisingID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('登榜',
    sa.Column('ChartID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MusicID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SongRanking', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ChartID'], ['榜单.ChartID'], name='登榜_ibfk_1'),
    sa.ForeignKeyConstraint(['MusicID'], ['音乐.MusicID'], name='登榜_ibfk_2'),
    sa.PrimaryKeyConstraint('ChartID', 'MusicID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('AdmID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('AdmName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Aassword', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('AdmID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('管理员')
    op.drop_table('广告')
    # ### end Alembic commands ###
