"""empty message

Revision ID: 4b2277f4ce61
Revises: 7c72b6227e23
Create Date: 2023-11-18 18:40:56.821082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2277f4ce61'
down_revision = '7c72b6227e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('榜单',
    sa.Column('ChartID', sa.Integer(), nullable=False),
    sa.Column('ChartType', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('ChartID')
    )
    op.create_table('管理员',
    sa.Column('AdminID', sa.Integer(), nullable=False),
    sa.Column('Password', sa.String(length=50), nullable=False),
    sa.Column('AdminName', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('AdminID'),
    sa.UniqueConstraint('AdminName')
    )
    op.create_table('登榜',
    sa.Column('MusicID', sa.Integer(), nullable=False),
    sa.Column('ChartID', sa.Integer(), nullable=False),
    sa.Column('SongRank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ChartID'], ['榜单.ChartID'], ),
    sa.ForeignKeyConstraint(['MusicID'], ['音乐.MusicID'], ),
    sa.PrimaryKeyConstraint('MusicID', 'ChartID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('登榜')
    op.drop_table('管理员')
    op.drop_table('榜单')
    # ### end Alembic commands ###
