"""empty message

Revision ID: 598fc9929ba7
Revises: b0b1fa34074d
Create Date: 2023-11-17 22:31:42.280398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '598fc9929ba7'
down_revision = 'b0b1fa34074d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('榜单',
    sa.Column('ChartID', sa.Integer(), nullable=False),
    sa.Column('ChartType', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('ChartID')
    )
    op.create_table('订单',
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.String(length=11), nullable=True),
    sa.Column('OrderTime', sa.DateTime(), nullable=False),
    sa.Column('DownloadStatus', sa.Enum('0', '1'), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['用户.UserID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('下单',
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('MusicID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MusicID'], ['音乐.MusicID'], ),
    sa.ForeignKeyConstraint(['OrderID'], ['订单.OrderID'], ),
    sa.PrimaryKeyConstraint('OrderID', 'MusicID')
    )
    op.create_table('登榜',
    sa.Column('ChartID', sa.Integer(), nullable=False),
    sa.Column('MusicID', sa.Integer(), nullable=False),
    sa.Column('SongRanking', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ChartID'], ['榜单.ChartID'], ),
    sa.ForeignKeyConstraint(['MusicID'], ['音乐.MusicID'], ),
    sa.PrimaryKeyConstraint('ChartID', 'MusicID')
    )
    with op.batch_alter_table('评论', schema=None) as batch_op:
        batch_op.alter_column('CommentTime',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('评论', schema=None) as batch_op:
        batch_op.alter_column('CommentTime',
               existing_type=mysql.DATETIME(),
               nullable=True)

    op.drop_table('登榜')
    op.drop_table('下单')
    op.drop_table('订单')
    op.drop_table('榜单')
    # ### end Alembic commands ###
