"""empty message

Revision ID: 73114713dfa0
Revises: 8557f25a132d
Create Date: 2023-11-20 18:38:31.057057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73114713dfa0'
down_revision = '8557f25a132d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('登榜',
    sa.Column('MusicID', sa.Integer(), nullable=False),
    sa.Column('ChartID', sa.Integer(), nullable=False),
    sa.Column('SongRanking', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ChartID'], ['音乐.MusicID'], ),
    sa.ForeignKeyConstraint(['MusicID'], ['音乐.MusicID'], ),
    sa.PrimaryKeyConstraint('MusicID', 'ChartID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('登榜')
    # ### end Alembic commands ###
