"""empty message

Revision ID: 7c72b6227e23
Revises: 
Create Date: 2023-11-17 20:41:57.602818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c72b6227e23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('captcha', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('歌手',
    sa.Column('SingerID', sa.Integer(), nullable=False),
    sa.Column('Singer', sa.String(length=30), nullable=False),
    sa.Column('SingerSex', sa.Enum('男', '女'), nullable=True),
    sa.PrimaryKeyConstraint('SingerID')
    )
    op.create_table('用户',
    sa.Column('UserID', sa.String(length=11), nullable=False),
    sa.Column('Password', sa.String(length=30), nullable=False),
    sa.Column('UserName', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.Enum('男', '女'), nullable=True),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('ContactNumber', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('类型',
    sa.Column('ClassID', sa.Integer(), nullable=False),
    sa.Column('TypeName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ClassID')
    )
    op.create_table('音乐',
    sa.Column('MusicID', sa.Integer(), nullable=False),
    sa.Column('ClassID', sa.Integer(), nullable=True),
    sa.Column('MusicName', sa.String(length=100), nullable=False),
    sa.Column('Intro', sa.String(length=200), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('StorageLocation', sa.String(length=300), nullable=False),
    sa.Column('IssueTime', sa.DateTime(), nullable=False),
    sa.Column('Cover', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['ClassID'], ['类型.ClassID'], ),
    sa.PrimaryKeyConstraint('MusicID')
    )
    op.create_table('演唱',
    sa.Column('SingerID', sa.Integer(), nullable=False),
    sa.Column('MusicID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MusicID'], ['音乐.MusicID'], ),
    sa.ForeignKeyConstraint(['SingerID'], ['歌手.SingerID'], ),
    sa.PrimaryKeyConstraint('SingerID', 'MusicID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('演唱')
    op.drop_table('音乐')
    op.drop_table('类型')
    op.drop_table('用户')
    op.drop_table('歌手')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
