"""empty message

Revision ID: 8557f25a132d
Revises: 3adb000efbc8
Create Date: 2023-11-20 18:32:58.402231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8557f25a132d'
down_revision = '3adb000efbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('榜单',
    sa.Column('ChartID', sa.Integer(), nullable=False),
    sa.Column('ChartType', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('ChartID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('榜单')
    # ### end Alembic commands ###
