"""empty message

Revision ID: b3b8b599713b
Revises: aef597877f18
Create Date: 2023-11-12 10:30:36.730263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3b8b599713b'
down_revision = 'aef597877f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('音乐', schema=None) as batch_op:
        batch_op.alter_column('MusicName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('StorageLocation',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('IssueTime',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('音乐', schema=None) as batch_op:
        batch_op.alter_column('IssueTime',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('StorageLocation',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('MusicName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
